FROM alpine:3.7

ENV FILEWATCH_VERSION 0.0.4

RUN apk --no-cache add ca-certificates

RUN wget https://github.com/olegsmetanin/filewatch/releases/download/$FILEWATCH_VERSION/filewatch-linux.tar.gz -O - | tar -xz -C /usr/local/bin
